# Generated by Django 4.1 on 2023-11-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_genere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('uuid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('genere', models.ManyToManyField(to='collection.genere')),
            ],
        ),
    ]
