# Generated by Django 4.1 on 2023-11-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(to='collection.movies'),
        ),
    ]
